version: 1.0.{build}  
image: Visual Studio 2017

environment:  
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"

install:  
  - docker version

build_script:  
  - docker build -t me/testdock .

test_script:  
  - docker run me/testdock

